server:
  address: 127.0.0.1
  port: 8080

spring:
  application:
    name: control-plane
  config:
    import: "optional:file:./.env[.properties],optional:file:../.env[.properties]"
  datasource:
    url: jdbc:postgresql://localhost:5432/${DATABASE}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
