server:
  address: 127.0.0.1
  port: 8080

spring:
  application:
    name: control-plane
  datasource:
    url: jdbc:postgresql://localhost:5432/agent_runner
    username: postgres
    password: admin
