CREATE TYPE run_status AS ENUM ('queued', 'running', 'succeeded', 'failed');
CREATE TABLE runs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    task text NOT NULL,
    status run_status NOT NULL DEFAULT 'queued',
    stage text DEFAULT 'not started',
    attempt int NOT NULL DEFAULT 0,
    worker_id text,
    claimed_at timestamptz,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);
CREATE TABLE run_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id UUID NOT NULL,
    CONSTRAINT fk_runs FOREIGN KEY (run_id) REFERENCES runs(id),
    stage text NOT NULL,
    message text,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_events_run_id ON run_events (run_id);